# VARIED MOBS by Tomhmagic - https://discord.gg/7eUecQ3sBT

# Debug mode will print extra information to the console, useful for debugging issues.
debugMode: false

enabled_worlds:
  - world
  - world_nether
  - world_the_end

scale:
  min: 0.75
  max: 1.25

# For a list of enabled entities, see https://github.com/Tomhmagic/VariedMobs/README.md
enabled_entities:
  - ARMIDILLO
  - BAT
  - BEE
  - BLAZE
  - CAT
  - CAVE_SPIDER
  - CHICKEN
  - COD
  - COW
  - CREEPER
  - DOLPHIN
  - DONKEY
  - DROWNED
  - ELDER_GUARDIAN
  - ENDERMAN
  - ENDERMITE
  - EVOKER
  - FOX
  - GHAST
  - GIANT
  - GUARDIAN
  - HOGLIN
  - HORSE
  - HUSK
  - ILLUSIONER
  - IRON_GOLEM
  - LLAMA
  - MAGMA_CUBE
  - MOOSHROOM
  - MULE
  - OCELOT
  - PANDA
  - PARROT
  - PHANTOM
  - PIG
  - PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - POLAR_BEAR
  - PUFFERFISH
  - RABBIT
  - RAVAGER
  - SALMON
  - SHEEP
  - SHULKER
  - SILVERFISH
  - SKELETON
  - SKELETON_HORSE
  - SLIME
  - SPIDER
  - SQUID
  - STRAY
  - STRIDER
  - TRADER_LLAMA
  - TROPICAL_FISH
  - TURTLE
  - VEX
  - VILLAGER
  - VINDICATOR
  - WANDERING_TRADER
  - WITCH
  - WITHER_SKELETON
  - WOLF
  - ZOGLIN
  - ZOMBIE
  - ZOMBIE_HORSE
  - ZOMBIE_VILLAGER
  - ZOMBIFIED_PIGLIN